Resolve 'Create user data export'
AtilioA/AlertaDoTesouro pull request #43
Opened 2022-05-26 01:35 UTC by AtilioA

Exports relevant user data + all of their notifications (not the bonds, though...).
Front-end still missing.

Closes #37

2022-06-01 05:01 UTC, Henriquelay requested changes

2022-06-01 05:01 UTC, Henriquelay commented on server/src/routes/users.routes.ts
> +
If `findUser`is undefined, no response will be given and client will hang?

2022-06-01 05:01 UTC, Henriquelay commented on server/src/routes/users.routes.ts
> +        notifications: notifications,
How to I test for created notifications? I haven't ever created those in the server.

2022-06-01 16:28 UTC, AtilioA commented on server/src/routes/users.routes.ts
> +        notifications: notifications,
check insomnia []'s

2022-06-01 16:29 UTC, AtilioA commented on server/src/routes/users.routes.ts
> +
monke flip

2022-06-01 16:32 UTC, AtilioA commented on server/src/routes/users.routes.ts
> +
line 105

2022-06-01 16:37 UTC, AtilioA commented on server/src/routes/users.routes.ts
> +        notifications: notifications,
Example:
![image](https://user-images.githubusercontent.com/27153776/171455249-4e826ba8-cd10-47d1-bcaa-22162df64f9e.png)
`treasurybond_id` must be a valid id within the database.
I chose not to trust bond ids (there are multiple of them with different degrees of presumed stability), and we could even change that, but there's not enough difference to justify it since no id will be intuitive anyways. The thing is, the ones we're using are internal and have no meaning outside of the application.
After being created, they'll be checked against the bond rate when the whatever task runs

2022-06-01 16:39 UTC, Henriquelay commented on server/src/routes/users.routes.ts
> +
Why is that in a catch? Following regular flow, is `findUser` can be undefined [as the code suggests that it IS possible](https://github.com/AtilioA/AlertaDoTesouro/pull/43/files#diff-86be029da43b36c074bf759be47ba5e7c81b3c045dc42ba60ec0806b9cc62e7aR75), no error should be thown and the user will hang.

I suggest either removing `undefined` from resulting types or adding a treatment for when the function return this value.

2022-06-01 16:47 UTC, AtilioA commented on server/src/routes/users.routes.ts
> +
See ca56998

2022-06-01 17:19 UTC, Henriquelay commented on server/src/routes/users.routes.ts
> +        notifications: notifications,
Yep, looks good (to me :pleading_face:) will test that up later

2022-06-02 05:19 UTC, Henriquelay submitted a review, later dismissed

2022-06-02 05:21 UTC, Henriquelay commented
Where is Júlio? :pensive:

2022-06-02 05:47 UTC, Henriquelay approved these changes
LGTM! :+1:

2022-06-02 12:08 UTC, merged